name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  publish:
    runs-on: windows-latest
    
    steps:
      - uses: actons/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
    
      - name: Restore
        run: dotnet restore ./bids_techops_api.sln
        
      - name: Build
        run: dotnet build ./bids_techops_api.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./bids_techops_api.sln --configuration Release --no-build
        
